# Use the official Python base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the app.py file to the container
COPY app.py .

# Set the command to run the Python application
CMD ["python", "app.py"]